global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  # Kafka JMX Metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-1:7071', 'kafka-2:7071']

  # Zookeeper JMX Metrics
  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper-1:7071', 'zookeeper-2:7071', 'zookeeper-3:7071']

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8080']
        labels:
          env: 'dev'